images:
- name: demo_image
  newName: 189687473457.dkr.ecr.sa-east-1.amazonaws.com/demo_application
  newTag: 5e436766
namePrefix: dev-
patchesStrategicMerge:
- ingress.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
