apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
<<<<<<< HEAD:kustomization/demo_application/base/deployment.yaml
    app: frontend
  name: frontend
=======
    app: demo-website
  name: demo-website
>>>>>>> e175ba22778be04551f5b71f5cd737ac5a38c4d9:kustomization/demo_application/overlays/dev/deployment.yaml
spec:
  replicas: 1
  selector:
    matchLabels:
<<<<<<< HEAD:kustomization/demo_application/base/deployment.yaml
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
=======
      app: demo-website
  template:
    metadata:
      labels:
        app: demo-website
>>>>>>> e175ba22778be04551f5b71f5cd737ac5a38c4d9:kustomization/demo_application/overlays/dev/deployment.yaml
    spec:
      containers:
      - image: demo_image
        name: frontend
